# Generated by Django 4.0 on 2023-04-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QSelection',
        ),
    ]
