# Generated by Django 4.0 on 2023-04-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('rtype', models.CharField(choices=[('C', 'Course'), ('A', 'Article'), ('B', 'Book'), ('V', 'Video'), ('O', 'Other')], max_length=1)),
                ('provider', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
