# Generated by Django 4.0 on 2023-04-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
