# Generated by Django 4.0 on 2023-04-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curriculum', '0003_curriculum_slug_alter_curriculum_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumsyllabi',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='syllabitopic',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
