# Generated by Django 4.0 on 2023-04-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curriculum', '0005_curriculum_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='curriculumsyllabi',
            name='order',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='curriculumsyllabi',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
