# Generated by Django 5.1.3 on 2024-11-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curriculum', '0010_alter_curriculum_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumreview',
            name='label',
            field=models.CharField(blank=True, choices=[('A', 'Course Content'), ('B', 'Exercises'), ('C', 'Course Structure'), ('D', 'Learning Experience'), ('E', 'Feature Request'), ('F', 'Improvement')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='curriculumreview',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('P', 'Positive'), ('N', 'Negative'), ('N', 'Neutral')], max_length=3, null=True),
        ),
    ]
