# Generated by Django 5.1.3 on 2024-11-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='label',
            field=models.CharField(blank=True, choices=[('A', 'Course Content'), ('B', 'Exercises'), ('C', 'Course Structure'), ('D', 'Learning Experience'), ('E', 'Feature Request'), ('F', 'Improvement')], max_length=1, null=True),
        ),
    ]
