# Generated by Django 4.0 on 2023-04-27 20:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('Curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('in_demand', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='RoadMap.jobrole')),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoadMap.roadmap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('rtype', models.CharField(choices=[('R', 'Required'), ('E', 'Elective')], max_length=1)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curriculum.curriculum')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoadMap.roadmap')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
